### ISSUE TITLE
Cannot import dumped xml from older version

### ISSUE THREAD

**Issue by lpvm** [levaidaniel/kc#3]
Hi Daniel,

In a Linux x86_64 system, I was using  `kc 2.5-dev-GIT_VERSION` from 30th of March 2017.
As I am assembling a new system, I've cloned kc today.

Tried to open the kcd file, but the program said that the password was wrong, and it isn't.
Then I dumped the contents of the database to a xml file, built the new version of `kc` and tried to import the dump with `import -k kc_dump.xml`.
`kc` says that the xml file `ERROR: Not a valid kc XML structure ('kc_dump.xml')!`.
There are multiple lines saying 
`kc_dump.xml:4: element keychain: validity error : Element keychain does not carry attribute created`.

The line 4 of the xml dump contains something like:
`  <keychain name="gmail" modified="1593778400" description="">  `

**Comment by levaidaniel** [comment]
Hey Luis!

It seems you've been running an older version (from 2015) of the development branch and now you've upgraded (pulled) to the latest that contains many changes that are incompatible with your database (created with an old version of kc).
As with most software, following a development branch requires care and attention towards new features, changes in features and incompatibilities introduced.
My advice is to check the changelog and the documentation carefully while doing this.

Having said that, after you read the changelog and figured out why could -- according to the error message -- a "created" attribute be missing from your XML document, check out the `-o` option of *import* that was introduced to resolve _some_ of these cases.

Let me know if you have troubles along the way.

-- 
Daniel

**Comment by lpvm** [comment]
Hi Dániel,

Thank you for your support.
I'm trying to install `kc` with pcre support.  These are the packages that are installed in Ubuntu:

```
libpcre2-16-0/focal,now 10.34-7 amd64 [installed,automatic]
libpcre2-32-0/focal,now 10.34-7 amd64 [installed,automatic]
libpcre2-8-0/focal,now 10.34-7 amd64 [installed,automatic]
libpcre2-dev/focal,now 10.34-7 amd64 [installed]
libpcre2-posix2/focal,now 10.34-7 amd64 [installed,automatic]
libpcre3/focal,now 2:8.39-12build1 amd64 [installed,automatic]
```

But the `make` command fails with the message:
```
cmd_searchre.c:27:10: fatal error: pcre.h: No such file or directory
   27 | #include <pcre.h>
```

Do I need any of these packages installed as well?
```
ibpcre3-dbg/focal 2:8.39-12build1 amd64
libpcre3-dev/focal 2:8.39-12build1 amd64
libpcre32-3/focal 2:8.39-12build1 amd64
libpcrecpp0v5/focal 2:8.39-12build1 amd64
libre2-5/focal 20200101+dfsg-1build1 amd64
libre2-dev/focal 20200101+dfsg-1build1 amd64
```
`find /usr/ -name 'pcre.h'`  didn't return any file indeed.

**Comment by levaidaniel** [comment]
It seems [libpcre3-dev](https://packages.ubuntu.com/eoan/amd64/libpcre3-dev/filelist) has _pcre.h_ nowadays on Ubuntu.

But it might be worth looking into the newer regex libraries on my end, and see if I can make this optional and choose what library to use during compilation.

Until then, your best bet is the above package.

--
Daniel
-------- Original Message --------

**Comment by lpvm** [comment]
Ok, it's done in Ubuntu.
I could also install it on VoidLinux as there are the `pcre` and `pcre-devel` that seem more obvious.
The import went fine using `importxml -o -k dump.xml` inside `kc`.

Thank you very much!
