### ISSUE TITLE
Compilation in aarch64 - Raspberry Pi 4

### ISSUE THREAD

**Issue by lpvm** [levaidaniel/kc#4]
I hoped that `kc` could compile on a aarch64 Linux distro installed in a Raspberry Pi 4.
The command `$ make -f Makefile.linux HAVE_PCRE=y` returns an error:

```
make -C bcrypt -f Makefile.linux
make[1]: Entering directory '/home/lupe/kc-2.4.2/bcrypt'
cc    -c -o sha2.o sha2.c
sha2.c:38:10: fatal error: sys/endian.h: No such file or directory
 #include <sys/endian.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: sha2.o] Error 1
make[1]: Leaving directory '/home/lupe/kc-2.4.2/bcrypt'
make: *** [Makefile.linux:63: bcrypt] Error 2
```
Is there any hope to have `kc` running in this system?

**Comment by levaidaniel** [comment]
You need to install a couple of supporting development packages for your libraries:
```
$ dpkg -S sys/endian.h
libbsd-dev:armhf: /usr/include/bsd/sys/endian.h
```
I tried this on a RPi 4 as well, but on armhf, this what was missing:
`sudo apt install libbsd-dev libxml2-dev libreadline-dev`

Hope this helps

ps.: if you want PCRE, then for that as well - but nowadays you can get away with libc's POSIX regex library, if you don't use any fancy PCRE syntax.

**Comment by lpvm** [comment]
I'm using a devuan image on the RPi 4.
The suggested `dpkg` command finds the file, but stiil the compilation fails with the same issue.
```
$ dpkg -S sys/endian.h
libbsd-dev:arm64: /usr/include/bsd/sys/endian.h

$ make -f Makefile.linux 
make -C bcrypt -f Makefile.linux
make[1]: Entering directory '/home/lupe/recolhidos/kc-2.4.2/bcrypt'
cc    -c -o sha2.o sha2.c
sha2.c:38:10: fatal error: sys/endian.h: No such file or directory
 #include <sys/endian.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: sha2.o] Error 1
make[1]: Leaving directory '/home/lupe/kc-2.4.2/bcrypt'
make: *** [Makefile.linux:63: bcrypt] Error 2
```

**Comment by levaidaniel** [comment]
Can you try with a latest pull from master?

**Comment by lpvm** [comment]
With the latest pull I was able to compile.
But it doesn't seem able to open the kc file of the stable version.
Haven't tried yet, but a dump and restore should suffice, no?

**Comment by levaidaniel** [comment]
It won't open the old database file, that's correct. Try the `-o` option of the `import` command, that should turn on legacy DTD parsing - the encryption parameters must be the same as with the old version.
If all else fails, a `dump` with the old version to XML and `importxml` on the new version should work - `importxml` also has a `-o` option for legacy XML files, try that if you can't seem to get it working.

Paste any error messages here with KC_DEBUG env. var set if nothing seems to work.

**Comment by lpvm** [comment]
The `import [-o]` didn't work, but the `dump` and `importxml` (no need for the `-o`) worked fine.
Although the last pull is not a release, I can assume it's as stable as the last release, right?
If so, it's time to update all `kc` installations so that a simple copy of the database keeps everything up to date.

Thank you very much @levaidaniel !  All the best to you.
