### ISSUE TITLE
Scripts are not POSIX shell compatible

### ISSUE THREAD

**Issue by diizzyy** [levaidaniel/kc#9]
At least typeset (https://github.com/levaidaniel/kc/blob/master/regress/cmd_passwd.sh#L37) isn't and given https://github.com/levaidaniel/kc/blob/master/.github/workflows/test.yml#L43 just use the proper shebang for bash.

There's also a reference here: https://github.com/levaidaniel/kc/blob/master/regress/run_tests.sh#L29

You can also try running the scripts using dash (https://wiki.archlinux.org/title/Dash) which will also fail on this.

**Comment by diizzyy** [comment]
I noticed this because of https://cgit.freebsd.org/ports/tree/security/kc/Makefile which basically forces bash for everything test related. Is there anything else to take into consideration?

**Comment by diizzyy** [comment]
Well, shebang should be switched to bash as sh isn't working?

**Comment by levaidaniel** [comment]
> Well, shebang should be switched to bash as sh isn't working?

This is the reason the `SH=${SHELL}` option is in the regression test script in the first place.
